.\" See LICENSE file for copyright and license details
.Dd 2022-10-31
.Dt SHRT 1
.Os
.Sh NAME
.Nm shrt
.Nd URL shortener and go-get handler
.Sh SYNOPSIS
.Nm
.Op Fl hv
.
.Sh DESCRIPTION
.Nm
is a URL shortener service (much like bit.ly without the trackers)
that also handles go-get requests.
The latter are a specific GET request query used by the Go programming
language toolchain to aid in the downloading of utilities and
libraries prior to build and installation.
.Pp
Upon invocation,
.Nm
reads the database file into memory and serves a single request
according to the Common Gateway Interface.
.Pp
Shortlinks are recorded in the database, and any request path not
matching a shortlink is assumed to be a go-get request.
This is by design, but can result in specious redirects.
Additionally, subdirectory paths are not allowed.
.Pp
Shortlinks generate an HTTP 301 response.
Go-get requests generate an HTTP 200 response.
If configured, requests to the base path (i.e., "/") generate an
HTTP 302 response.
.Pp
The database file is human-readable and formatted according to
.Xr shrtfile 5 ,
basically a key-value store.
In order to add a new shortlink to the database, simply edit the file.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h
Print usage and exit.
.It Fl v
Print version and exit.
.El
.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr shrtfile 5
.br
RFC 7231: Hypertext Transfer Protocol (HTTP/1.1): Semantics and
Content
.br
RFC 3875: The Common Gateway Interface (CGI) Version 1.1
.Pp
.Lk https://golang.org/doc/articles/go_command.html?h=go+get "About the go command"
.Sh HISTORY
.Nm
began in November 2020.
.Sh AUTHORS
.Nm
was written by
.An Daniel Moch Aq Mt daniel@danielmoch.com .
