.\" See LICENSE file for copyright and license details
.Dd 2020-12-06
.Dt SHRTFILE 5
.Os
.Sh NAME
.Nm shrtfile ,
.Nm shrt.db
.Nd URL shortener data files
.
.Sh DESCRIPTION
Shrtfiles are simple key-value values used by the
.Xr shrt 1
URL shortener.
The syntax of the file is human readable.
Each line represents a key-value pair.
The key is everything to the left of the first equals sign, and the
value is everything to the right.
Whitespace is trimmed from the beginning and end of both keys and
values.
.Pp
.Pa shrt.db
Is a shrtfile containing all of the shortlinks recognized by the server.
The key is the shortlink (i.e., the request path), and the value
is the redirect URL.
Keys should not contain path separators (i.e., foward slashes).
.
.Sh FILES
shrt.db
.El
.Sh SEE ALSO
.Xr shrt 1
